data = {
    firstNames: ["Eloise","Aurelia","Ava","Rose","Maeve","Esme","Eleanor","Imogen","Aurora","Ophelia","Freya","Luna","Alice","Iris","Ivy","Isla","Olivia","Hazel","Astrid","Amelia","Genevieve","Charlotte","Aria","Elodie","Violet","Sienna","Cora","Nora","Ottilie","Daphne"],
    lastNames: ["Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson"],
    title: ["Network architect","Systems analyst","Network engineer","Wireless network engineer","Database analyst","SQL database administrator","Back-end developer","Cloud/software developer","Cloud/software applications engineer","DevOps engineer","Front-end developer","Full-stack developer","Java developer","Platform engineer","Software engineer","UI designer","UX designer","Web developer","Product designer","Data analyst","Data analytics developer","Data scientist"],
    school: ["Athabasca University","Augustana University College","Concordia University College of Alberta","DeVry Institute of Technology","The King's University","Mount Royal College","University of Alberta","University of Calgary","University of Lethbridge","British Columbia Institute of Technology","Open Learning Agency","Royal Roads University","Simon Fraser University","Technical University of British Columbia","Trinity Western University","University of British Columbia","University of Northern British Columbia","University of Victoria","Camosun College","Brandon University","University of Manitoba","University of Winnipeg","Mount Allison University","Saint Thomas University","Universite de Moncton","University of New Brunswick, Fredericton","University of New Brunswick, Saint John","Memorial University of Newfoundland","Sir Wilfred Grenfell College","Acadia University","Dalhousie University","University of King’s College","Mount St. Vincent University","Nova Scotia Agricultural College","NSCAD University","Nova Scotia Teachers College","St. Francis Xavier University","St. Mary's University","Université Sainte-Anne","University College of Cape Breton","Brock University","Carleton University","Collège Universitaire Dominicain","Lakehead University","Laurentian University of Sudbury","McMaster University","Nipissing University","Ontario College of Art","Queen's University","Royal Military College of Canada","Ryerson Polytechnic University","Trent University","University of Guelph","University of Ottawa","University of Toronto","University of Waterloo","University of Western Ontario","University of Windsor","Wilfrid Laurier University","York University","University of Prince Edward Island","Bishop's University","College Militaire Royale","Concordia University","Ecole des Hautes Etudes Commerciales","Ecole Polytechnique","McGill University","Universite de Montreal","Universite du Quebec, central","Universite de Sherbrooke","Universite Laval","University of Regina","University of Saskatchewan","St. Thomas More College"],
    questionOne:["Reading","Travelling","Sports","Fishing","Crafting","Collecting","Music","Gardening","Art","Yoga","Cooking","Hiking","Video games","Television","Learning about my career"],
    questionTwo:["Design","Front-end developement","Back-end developement","Big data","Networking","Blockchain","Business and strategy"]
}

export {data}